services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./tmp/backend_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3005:3000"
    env_file:
      - .env
    depends_on:
      - backend
