services:
  backend:
    build: ./backend
    network_mode: host
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAL_KEY=${FAL_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_PATH=/app/app.db
      - BACKEND_CORS_ORIGINS=http://localhost:3005
      - FRONTEND_URL=http://localhost:3005
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3005:3000"
    # DISABLED - volumes:
    #   - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  backend_data:


