version: '3.9'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 5005 --reload
    ports:
      - "5005:5005"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5005
      - BACKEND_CORS_ORIGINS=http://localhost:3005
      - SESSION_SECRET=change-me-in-production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - FRONTEND_URL=http://localhost:3005
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "3005:3005"
    environment:
      - VITE_BACKEND_URL=http://backend:5005
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules


